# Шаг 1: Сборка бинарного файла
FROM golang:latest AS builder

# Установим рабочую директорию внутри контейнера
WORKDIR /app

# Клонируем репозиторий с GitHub
RUN git clone https://github.com/aid219/rabskie-opovesheniya.git .

# Установим зависимости
RUN go mod tidy

# Скомпилируем бинарный файл
# RUN go build -o main .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
# Шаг 2: Сборка минимального конечного образа
FROM scratch

# Скопируем скомпилированный бинарный файл из этапа сборки
COPY --from=builder /app/main /
COPY local.yaml .
# Укажем команду для запуска приложения
CMD ["/main"]