
# 1150762777

messangers:
  - "telegram"
  - "email"

telegram:
  - "token": "7191966794:AAEOt99eIGICjTcB0Fobz8hWMCD_2uU-gfw"

email:
  - "sender": "qum.my@yandex.ru"
  - "host": "smtp.yandex.ru"
  - "port": 587
  - "username": "qum.my@yandex.ru"
  - "password": "ltpiedglwsdvbomb"

rabbit:
  - "host": "amqp://guest:guest@localhost:5672/"
  - "queue": "rabbitsLoveAnal"
